/** Shared status and controls for verified asset downloads. */
export const downloadStatusCopy = {
  english: {
    checking: 'Checking download…',
    missing: 'Not downloaded',
    paused: 'Download paused',
    downloading: 'Downloading',
    retrying: 'Retrying connection…',
    verifying: 'Verifying download…',
    downloaded: 'Downloaded · available offline',
    failed: 'Download unavailable · check connection and storage',
    restart: 'Model update · ready for next app launch',
    searchLabel: 'Search',
    ready: 'Ready · available offline',
    unsupported: 'Not available on this phone',
  },
  tagalog: {
    checking: 'Sinusuri ang download…',
    missing: 'Hindi pa na-download',
    paused: 'Naka-pause ang download',
    downloading: 'Dina-download',
    retrying: 'Sinusubukang kumonekta muli…',
    verifying: 'Bineberipika ang download…',
    downloaded: 'Na-download na · magagamit offline',
    failed: 'Hindi makumpleto ang download · suriin ang koneksiyon at storage',
    restart: 'Bagong modelo · handa sa susunod na pagbukas ng app',
    searchLabel: 'Paghahanap',
    ready: 'Handa na · magagamit offline',
    unsupported: 'Hindi magagamit sa teleponong ito',
  },
  cebuano: {
    checking: 'Gisusi ang download…',
    missing: 'Wala pa ma-download',
    paused: 'Naka-pause ang download',
    downloading: 'Gi-download',
    retrying: 'Gisulayang mokonekta pag-usab…',
    verifying: 'Gipamatud-an ang download…',
    downloaded: 'Na-download na · magamit offline',
    failed: 'Dili makompleto ang download · susiha ang koneksiyon ug storage',
    restart: 'Bag-ong modelo · andam sa sunod nga pag-abli sa app',
    searchLabel: 'Pagpangita',
    ready: 'Andam na · magamit offline',
    unsupported: 'Dili magamit niining telepono',
  },
};

export const downloadControlsCopy = {
  english: {title: 'AI downloads', detail: 'Search and tutor models download automatically. Pausing keeps downloaded files and progress.', pause: 'Pause downloads', resume: 'Resume downloads', error: 'Could not save this setting. Please try again.'},
  tagalog: {title: 'Mga download ng AI', detail: 'Awtomatikong dina-download ang mga modelo para sa paghahanap at tutor. Hindi mabubura ang mga na-download kapag naka-pause.', pause: 'I-pause ang download', resume: 'Ipagpatuloy ang download', error: 'Hindi na-save ang setting. Subukan muli.'},
  cebuano: {title: 'Mga download sa AI', detail: 'Awtomatikong i-download ang mga modelo para sa pagpangita ug tutor. Dili mapapas ang mga na-download kon naka-pause.', pause: 'I-pause ang download', resume: 'Ipadayon ang download', error: 'Wala ma-save ang setting. Sulayi pag-usab.'},
};
