#!/usr/bin/env python3
"""Tala's card catalog: which subcategory every card and quiz question belongs to.

A student's phone reports what it showed as a bare id — `card_id` on a card view, the
question's fact id on a graded quiz — and Tala has to turn that into the subcategory the
student app shows on its calendar pills ("Mammals", "States of Matter"). The lookup lives in
Tala, not in the events, on purpose: there are far more student installs than Tala installs,
an old student build keeps sending bare ids for as long as it is in the field, and only Tala
can be updated cheaply.

  python3 packages/tala/scripts/build-card-catalog.py            # merge the current inventory
  python3 packages/tala/scripts/build-card-catalog.py --check    # fail if the file is stale

The inventory is what the student app itself draws from, built the way cards.ts builds it:
POOL is the card index plus the lesson-supplement cards, and the questions are the index's
questionFactIds plus the supplement's own. The supplement files are found by reading
lessonSupplement.ts's imports, so a new grade file cannot be missed.

rag/pipeline/build-cards-db.py runs this after every rebuild of the card index, so the
catalog cannot fall behind the inventory, and Tala's Gradle build runs --check so a stale one
cannot ship. The check is on CONTENT, not the index's dbVersion stamp: that stamp hashes the
card database's bytes, which change on every rebuild and on a facts-only restamp even when no
card id or subcategory did.

The catalog only ever GROWS. A card retired from the inventory is still on every phone that
has not updated, and still reaches Tala, so an id that leaves the inventory keeps its last
known subcategories. Ids are never re-used — ffct/dcard ids are append-only upstream — which is
what makes keeping them safe. When an id is still present its CURRENT subcategories win.

What is kept is taken from the COMMITTED catalog (HEAD, plus the other side of a merge in
progress), not from the working file. So deleting or mangling the file cannot silently drop a
retired id, ids minted by an experimental local build that was then reverted do not linger, and
--check fails on either — the file must equal the committed catalog merged with the current
inventory. Outside a git checkout, or before the catalog is first committed, the working file
is the base instead.

Format (UTF-8, tab-separated, one record per line, `#` lines are comments):
  T       <taxonomy id>  <label as the student app prints it on a pill>
  C       <card id>      <comma-separated T line numbers, 0-based, in T order>
  F       <fact id>      <same, for a quiz question's fact>
Several taxonomy ids can share one label ("States of Matter" is three); Tala merges them.
"""
import argparse, json, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
INDEX = os.path.join(ROOT, 'packages/mobile/src/generated/cardsIndex.generated.json')
CARDS_TS = os.path.join(ROOT, 'packages/mobile/src/data/cards.ts')
SUPPLEMENT_TS = os.path.join(ROOT, 'packages/mobile/src/data/lessonSupplement.ts')
OUT = os.path.join(ROOT, 'packages/tala/android/app/src/main/assets/card-catalog.tsv')

HEADER = """\
# Tala card catalog — GENERATED by packages/tala/scripts/build-card-catalog.py. Do not edit.
# Card and quiz ids -> the student app's subcategories. Append-only: see the script.
"""


def title_minor(cards_ts: str) -> set:
    """The student app's list of words title case leaves lower-case, read from its source.

    Read rather than copied so the pills and Tala can never disagree about "States of
    Matter" — the same way build-cards-db.py reads the search stop list out of cards.ts.
    """
    m = re.search(r'^const TITLE_MINOR = new Set\(\s*\((.*?)\)\.split\(\' \'\)', cards_ts, re.M | re.S)
    if not m:
        raise SystemExit('build-card-catalog: cannot find TITLE_MINOR in cards.ts; declaration changed')
    body = re.sub(r'//[^\n]*', '', m.group(1))
    words = ''.join(re.findall(r"'([^']*)'", body)).split(' ')
    if not words or any(not re.fullmatch(r'[a-zñ]+', w) for w in words):
        raise SystemExit(f'build-card-catalog: TITLE_MINOR parsed to non-words: {words[:8]}')
    return set(words)


def capitalise(word: str) -> str:
    """cards.ts `capitalise`: a word that already carries a capital (DNA, pH) is left alone."""
    if re.search(r'[A-Z]', word):
        return word
    m = re.search(r'[a-z0-9ñ]', word, re.I)
    return word if not m else word[:m.start()] + word[m.start()].upper() + word[m.start() + 1:]


def title_case(label: str, minor: set) -> str:
    """cards.ts `titleCase`, which is what turns a taxonomy label into a calendar pill."""
    words = label.split()
    return ' '.join(w.lower() if 0 < i < len(words) - 1 and w.lower() in minor else capitalise(w)
                    for i, w in enumerate(words))


def read(path: str) -> str:
    with open(path, encoding='utf-8') as f:
        return f.read()


def supplement_files(supplement_ts_path: str) -> list:
    """The lesson-supplement JSON files lessonSupplement.ts spreads into the student's pool."""
    source = read(supplement_ts_path)
    imports = re.findall(r"^import (\w+) from '\./([\w.-]+\.json)';", source, re.M)
    unused = [name for name, _ in imports
              if f'...{name}.cards' not in source or f'...{name}.questions' not in source]
    if not imports or unused:
        raise SystemExit('build-card-catalog: cannot read the lesson supplement files out of '
                         f'lessonSupplement.ts (imports {len(imports)}, not spread: {unused}); '
                         'its shape changed')
    return [os.path.join(os.path.dirname(supplement_ts_path), path) for _, path in imports]


def parse_catalog(text: str):
    """A catalog's records as id-keyed maps, so a merge never depends on line numbers."""
    rows = [line.split('\t') for line in text.splitlines() if line.strip() and not line.startswith('#')]
    order, labels, cards, facts = [], {}, {}, {}
    for row in rows:
        if len(row) != 3 or row[0] not in ('T', 'C', 'F'):
            raise SystemExit(f'build-card-catalog: unreadable catalog line {row!r} '
                             '(unresolved merge conflict? take either side and rerun)')
        if row[0] == 'T':
            order.append(row[1])
            labels[row[1]] = row[2]
    for kind, key, value in rows:
        if kind in ('C', 'F'):
            (cards if kind == 'C' else facts)[key] = [order[int(i)] for i in value.split(',')]
    return labels, cards, facts


def committed_catalogs(out_path: str) -> list:
    """The catalog as committed at HEAD, and at MERGE_HEAD while a merge is in progress."""
    rel = os.path.relpath(out_path, ROOT)
    texts = []
    for rev in ('HEAD', 'MERGE_HEAD'):
        try:
            shown = subprocess.run(['git', '-C', ROOT, 'show', f'{rev}:{rel}'],
                                   capture_output=True, text=True, encoding='utf-8')
        except FileNotFoundError:  # no git: a source tarball
            return []
        if shown.returncode == 0:
            texts.append(shown.stdout)
    return texts


def merge(catalog, taxonomy, cards_in, questions, minor):
    labels, cards, facts = (dict(part) for part in catalog)
    for leaf in taxonomy:
        labels[leaf['id']] = title_case(leaf['label_en'], minor) or leaf['id']
    by_fact = {}
    for card in cards_in:
        cats = card.get('cats') or []
        if cats:
            cards[card['id']] = list(dict.fromkeys(cats))
            by_fact.setdefault(card.get('factId') or '', []).append(cards[card['id']])
    # A quiz is about a FACT, and a few facts sit on more than one card (463 of ~48,600, and 212
    # of those disagree on subcategory). The quiz counts under all of them, most-shared first —
    # the same way a card in two subcategories counts under both.
    for fact in questions:
        groups = by_fact.get(fact)
        if not groups:
            continue
        tally = {}
        for cats in groups:
            for c in cats:
                tally[c] = tally.get(c, 0) + 1
        facts[fact] = sorted(tally, key=lambda c: -tally[c])  # stable: ties keep first appearance
    missing = sorted({c for cats in list(cards.values()) + list(facts.values()) for c in cats} - set(labels))
    if missing:
        raise SystemExit(f'build-card-catalog: subcategories with no label: {missing[:8]}')
    return labels, cards, facts


def render(labels, cards, facts) -> str:
    # Exactly the grammar Tala's parser accepts: three non-empty tab-free fields per line.
    for kind, table in (('subcategory', labels), ('card', cards), ('fact', facts)):
        bad = [k for k in table if not k or re.search(r'[\t\n\r,]', k)]
        if bad:
            raise SystemExit(f'build-card-catalog: {kind} ids that cannot be written: {bad[:5]}')
    bad = [t for t, label in labels.items() if not label.strip() or re.search(r'[\t\n\r]', label)]
    if bad:
        raise SystemExit(f'build-card-catalog: subcategory labels that cannot be written: {bad[:5]}')
    order = sorted(labels)
    at = {t: i for i, t in enumerate(order)}
    out = [HEADER]
    out += [f'T\t{t}\t{labels[t]}\n' for t in order]
    out += [f'C\t{k}\t{",".join(str(at[c]) for c in cards[k])}\n' for k in sorted(cards)]
    out += [f'F\t{k}\t{",".join(str(at[c]) for c in facts[k])}\n' for k in sorted(facts)]
    return ''.join(out)


def build(index_paths, base_texts=(), cards_ts_path=None, supplement_ts_path=None) -> str:
    """The catalog: every base catalog, then each index in order, with the current supplement."""
    minor = title_minor(read(cards_ts_path or CARDS_TS))
    supplement_cards, supplement_questions = [], []
    for path in supplement_files(supplement_ts_path or SUPPLEMENT_TS):
        grade = json.loads(read(path))
        supplement_cards += grade.get('cards', [])
        supplement_questions += list(grade.get('questions', {}))
    catalog = ({}, {}, {})
    for text in base_texts:
        base = parse_catalog(text)
        catalog = tuple({**mine, **theirs} for mine, theirs in zip(catalog, base))
    for path in index_paths:
        index = json.loads(read(path))
        catalog = merge(catalog, index['taxonomy'], index['cards'] + supplement_cards,
                        index.get('questionFactIds', []) + supplement_questions, minor)
    return render(*catalog)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--index', action='append',
                    help='card index to merge (repeatable, merged in order); default: the current one')
    ap.add_argument('--out', default=OUT)
    ap.add_argument('--check', action='store_true', help='exit 1 if the catalog is not up to date')
    args = ap.parse_args(argv)
    out = os.path.abspath(args.out)
    current = read(out) if os.path.exists(out) else None
    # Kept ids come from what was committed; only the shipped catalog has a committed version.
    base = committed_catalogs(out) if out == OUT else []
    if not base and current is not None:
        base = [current]
    text = build(args.index or [INDEX], base)
    if args.check:
        if text != current:
            print(f'build-card-catalog: {os.path.relpath(out, ROOT)} is stale — '
                  'run python3 packages/tala/scripts/build-card-catalog.py', file=sys.stderr)
            return 1
        return 0
    if text != current:
        os.makedirs(os.path.dirname(out), exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=os.path.dirname(out), suffix='.tmp')
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write(text)
        os.replace(tmp, out)
    counts = {k: text.count(f'\n{k}\t') for k in 'TCF'}
    print(f'  tala card catalog: {counts["T"]} subcategories, {counts["C"]:,} cards, '
          f'{counts["F"]:,} quiz facts ({len(text.encode()) / 1e6:.2f} MB)'
          f'{"" if text != current else " — unchanged"}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
