#!/usr/bin/env python3
"""Coverage roundup per competency and per grade×quarter: feed cards (pool), cards once the engravings are wired,
bank facts, DepEd-module cards, Lane A rows pending append, floors and laggards. Multi-label: a card counts under
every code it serves (agreement-tier labels, confidence >= 0.5). Writes rag/bank/COVERAGE-ROUNDUP.md + .json."""
import json, glob, os, collections
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
comp = {}
for f in sorted(glob.glob(f"{ROOT}/rag/sources/curriculum-guides/matatag-*-competencies.json")):
    for q in json.load(open(f))["quarters"]:
        for c in q["competencies"]: comp[c["code"]] = dict(grade=q["grade"], quarter=q["quarter"], domain=q["domain"], text=c["text"])
kinds = json.load(open(f"{ROOT}/rag/bank/competency-kinds.json"))["competencies"] if os.path.exists(f"{ROOT}/rag/bank/competency-kinds.json") else {}
T = json.load(open(f"{ROOT}/rag/bank/curriculum-tags.json"))["factoids"]
pool = {c["id"] for c in json.load(open(f"{ROOT}/rag/pipeline/cardsPool.app.json"))["cards"]}
webp = {os.path.basename(p)[:-5] for p in glob.glob(f"{ROOT}/packages/images/factoid-webp/*.webp")}
fact_of = {}
for l in open(f"{ROOT}/rag/bank/factoids.jsonl"):
    r = json.loads(l); fact_of[r["id"]] = r.get("factId")
bank_ids = {json.loads(l)["id"] for l in open(f"{ROOT}/rag/bank/science-facts.jsonl")}
cards, wired, facts, dlab = collections.Counter(), collections.Counter(), collections.defaultdict(set), collections.Counter()
labelled_facts = set()
for i, t in T.items():
    if t["confidence"] < 0.5: continue
    fid = fact_of.get(i); 
    if fid: labelled_facts.add(fid)
    for c in t.get("codes", [t["competency"]]):
        if c not in comp: continue
        if i.startswith("dcard-"): dlab[c] += 1; continue   # DepEd-module cards (card-ui pool), labelled per code
        if i in pool: cards[c] += 1
        if i in pool or i in webp: wired[c] += 1
        if fid: facts[c].add(fid)
# DepEd module cards (grade/quarter known, no MATATAG code) — cell-level supply only
dcards = collections.Counter(); dpath = f"{ROOT}/rag/pipeline/cardsPool.deped.v3.json"
if os.path.exists(dpath):
    for c in json.load(open(dpath)).get("cards", []):
        g, q = c.get("grade"), c.get("quarter")
        if g and q and (c.get("slug") or c.get("image")): dcards[(int(g), int(q))] += 1
# Lane A pending
lane = collections.Counter()   # Lane rows NOT yet in the bank (once appended they are counted through their labelled factoid)
for fn in glob.glob(f"{ROOT}/rag/pipeline/lane-a/out/lane-*-ingest-ready*.jsonl"):
    for l in open(fn):
        r = json.loads(l)
        if r["id"] not in bank_ids: lane[r["brief_code"]] += 1
rows = []
for code, m in comp.items():
    k = kinds.get(code, {}); fa = k.get("fact_able", 5)
    floor = 0 if fa < 3 else {5: 40, 4: 30, 3: 20}.get(fa, 40)
    rows.append(dict(code=code, grade=m["grade"], quarter=m["quarter"], domain=m["domain"], kind=k.get("kind", "content"), fact_able=fa, floor=floor,
                     cards=cards[code], cards_if_wired=wired[code], facts=len(facts[code]), dcards=dlab[code], lane_a=lane[code],
                     after_all=wired[code] + dlab[code] + lane[code], text=m["text"]))
for r in rows: r["laggard"] = r["floor"] > 0 and r["after_all"] < r["floor"]
cells = collections.defaultdict(lambda: dict(cards=0, cards_if_wired=0, facts=0, dcards=0, lane_a=0, competencies=0, below_floor_now=0, laggards=0))
for r in rows:
    c = cells[(r["grade"], r["quarter"])]; c["competencies"] += 1
    for k in ("cards", "cards_if_wired", "facts", "lane_a"): c[k] += r[k]
    c["dcards_labelled"] = c.get("dcards_labelled", 0) + r["dcards"]
    c["below_floor_now"] += (r["floor"] > 0 and r["cards"] < r["floor"]); c["laggards"] += r["laggard"]
for (g, q), n in dcards.items(): cells[(g, q)]["dcards"] = n
unlabelled_bank = len(bank_ids - labelled_facts)
summary = dict(competencies=len(rows), pool_cards=len(pool), engravings=len(webp), bank_facts=len(bank_ids), bank_facts_labelled=len(labelled_facts & bank_ids),
               bank_facts_unlabelled=unlabelled_bank, lane_a_pending=sum(lane.values()), below_floor_now=sum(1 for r in rows if r["floor"] > 0 and r["cards"] < r["floor"]),
               laggards_after_wiring_and_lane_a=sum(1 for r in rows if r["laggard"]))
json.dump(dict(summary=summary, cells={f"G{g}-Q{q}": v for (g, q), v in sorted(cells.items())}, competencies=rows), open(f"{ROOT}/rag/bank/COVERAGE-ROUNDUP.json", "w"), indent=1, ensure_ascii=False)
L = [f"# Coverage roundup — cards and facts per competency (generated by rag/pipeline/coverage-roundup.py)\n",
     f"Pool cards {len(pool):,} · engravings on disk {len(webp):,} · bank facts {len(bank_ids):,} ({len(labelled_facts & bank_ids):,} labelled via their factoid, {unlabelled_bank:,} never rewritten to a factoid = unlabelled) · Lane A pending {sum(lane.values())}.",
     "Multi-label: a card counts under every competency it serves. **cards** = in the shipping pool today; **wired** = pool + engraving-backed factoids once wired; **module cards** = DepEd-module cards in the card-ui pool with a competency label; **after all** = wired + module cards + Lane A. Floors 40/30/20 by fact-ability (0 = not fact-shaped).\n",
     "## Per grade × quarter\n", "| cell | competencies | cards now | wired | module cards (labelled / cell-only) | bank facts | Lane A | below floor now | laggards after all |", "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
for (g, q), c in sorted(cells.items()):
    L.append(f"| G{g} Q{q} | {c['competencies']} | {c['cards']} | {c['cards_if_wired']} | {c.get('dcards_labelled', 0)} / {c['dcards']} | {c['facts']} | {c['lane_a']} | {c['below_floor_now']} | **{c['laggards']}** |")
L += ["\n## Laggards — fact-able competencies still below floor after wiring the engravings and appending Lane A\n", "| code | cell | kind | floor | cards now | wired | module cards | Lane A | after all | competency |", "|---|---|---|---:|---:|---:|---:|---:|---:|---|"]
for r in sorted([r for r in rows if r["laggard"]], key=lambda r: (r["after_all"] - r["floor"], r["code"])):
    L.append(f"| `{r['code']}` | G{r['grade']} Q{r['quarter']} | {r['kind']} | {r['floor']} | {r['cards']} | {r['cards_if_wired']} | {r['dcards']} | {r['lane_a']} | **{r['after_all']}** | {r['text'][:90]} |")
L += ["\n## Every competency (sorted by cards now)\n", "| code | cell | floor | cards | wired | facts | Lane A | after all | flag |", "|---|---|---:|---:|---:|---:|---:|---:|---|"]
for r in sorted(rows, key=lambda r: (r["cards"], r["code"])):
    flag = "LAGGARD" if r["laggard"] else ("below floor now" if r["floor"] > 0 and r["cards"] < r["floor"] else ("not fact-shaped" if r["floor"] == 0 else ""))
    L.append(f"| `{r['code']}` | G{r['grade']} Q{r['quarter']} | {r['floor']} | {r['cards']} | {r['cards_if_wired']} | {r['facts']} | {r['lane_a']} | {r['after_all']} | {flag} |")
open(f"{ROOT}/rag/bank/COVERAGE-ROUNDUP.md", "w").write("\n".join(L) + "\n")
print(json.dumps(summary)); print("\n".join(L[4:4+2+len(cells)]))
print("\nLAGGARDS (%d):" % summary["laggards_after_wiring_and_lane_a"]); [print("  %-8s G%dQ%d floor %2d | now %3d | wired %3d | +laneA %2d → %3d | %s" % (r["code"], r["grade"], r["quarter"], r["floor"], r["cards"], r["cards_if_wired"], r["lane_a"], r["after_all"], r["text"][:70])) for r in sorted(rows, key=lambda r: r["after_all"]) if r["laggard"]]
