import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { MemoryFactSource } from './FactSource.js';
import type { ScienceFact } from './types.js';

/**
 * Read the fact bank straight from its source of truth, `rag/bank/science-facts.jsonl`.
 *
 * NODE ONLY, and deliberately not re-exported from `./index.js`: it imports `node:fs`, and
 * anything reachable from the app's entry point ends up in the Metro graph. The phone reads
 * the bank out of `cards.db` (see SqlFactSource) and must never reach this file. Consumers
 * outside the workspace packages import it by path; `@hiraia/shared` exposes it as the
 * separate `@hiraia/shared/node` entry point so that the split is explicit at the import.
 *
 * This replaces `packages/shared/src/rag/facts.generated.ts`, a 43.5 MB TypeScript array
 * compiled from this same JSONL. Every Node consumer was reading a transcription of a file
 * that was sitting right there — and the transcription had to be regenerated by hand after
 * every bank edit, which is a class of staleness that simply cannot happen now.
 *
 * ORDER IS LOAD-BEARING. Line N of the JSONL is fact ordinal N, and
 * `packages/mobile/assets/rag/vectors-labse.i8.bin` is positional: vector i belongs to bank
 * row i, and `RagStore.attachSemantic` refuses an index whose count disagrees. So the array
 * is returned in file order, never sorted or filtered.
 */
const BANK_REL = join('rag', 'bank', 'science-facts.jsonl');

/**
 * Where to find the bank. `HIRAIA_FACT_BANK` wins outright (an eval against a candidate bank,
 * a checkout laid out differently on the VPS); otherwise the first candidate that exists.
 *
 * TWO candidate families, because the two runtimes disagree about where this module IS.
 * Under tsx/node the file sits at packages/shared/src/rag/, so the repo root is four levels
 * up from `import.meta.url` — but the web demo's server code is WEBPACK-BUNDLED (Next
 * transpiles @hiraia/shared), and webpack rewrites `import.meta.url` to point at the output
 * chunk in .next/server/. Resolving from there lands nowhere. So the cwd and its ancestors
 * are searched too, which is the same escape hatch `packages/web/src/server/rag.ts` already
 * uses to find the vectors blob.
 */
function candidates(): string[] {
  const out: string[] = [];
  try {
    out.push(join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', BANK_REL));
  } catch {
    /* no usable import.meta.url (bundled CJS) — the cwd walk below covers it */
  }
  let d = process.cwd();
  for (let i = 0; i < 8; i++) {
    out.push(join(d, BANK_REL));
    const up = dirname(d);
    if (up === d) break;
    d = up;
  }
  return out;
}

export function factBankPath(): string {
  const override = process.env.HIRAIA_FACT_BANK;
  if (override) return override;
  const tried = candidates();
  for (const c of tried) if (existsSync(c)) return c;
  throw new Error(
    `fact bank not found. Set HIRAIA_FACT_BANK, or run from the repo. Tried:\n  ${tried.join('\n  ')}`
  );
}

export function loadFactBank(path: string = factBankPath()): ScienceFact[] {
  const out: ScienceFact[] = [];
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const r = JSON.parse(line) as ScienceFact & { unverified?: boolean };
    // Keep EXACTLY the nine ScienceFact fields, which is what the old generated array held
    // and what the `fact` table stores. 18 bank rows carry a working `unverified` flag; if it
    // survived here, a Node consumer's fact objects would differ from the phone's for those
    // rows, and the whole value of this migration is that they cannot.
    out.push({
      id: r.id,
      domain: r.domain,
      topic: r.topic,
      grades: r.grades,
      terms: r.terms,
      fact: r.fact,
      source: r.source,
      generator: r.generator,
      reviewed: r.reviewed,
    });
  }
  if (out.length === 0) throw new Error(`fact bank is empty: ${path}`);
  return out;
}

/**
 * `md5(science-facts.jsonl)[:12]` — the stamp `rag/scripts/build-vectors.py` writes into
 * `vectors-labse.meta.json` and `rag/pipeline/build-facts-db.py` writes into `fact_meta`.
 * Comparing them is how a caller proves the vectors blob and the bank are the same version.
 */
export function bankFileHash(path: string = factBankPath()): string {
  return createHash('md5').update(readFileSync(path)).digest('hex').slice(0, 12);
}

/**
 * The bank as a ready-to-use `FactSource`, stamped with its content hash.
 *
 * Use this rather than `new RagStore(loadFactBank())` wherever a semantic blob gets attached:
 * the hash lets `attachSemantic` reject a blob built for a DIFFERENT bank of the same size,
 * which the count check alone cannot see. Hashing 43 MB costs ~60 ms, once per process.
 */
export function loadFactSource(path: string = factBankPath()): MemoryFactSource {
  return new MemoryFactSource(loadFactBank(path), bankFileHash(path));
}
