const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

// Lets release builds fetch downloads from the provisioning laptop's LAN mirror, which serves
// plain HTTP at a private IPv4 address that the phone's device owner supplies at runtime
// (src/config/assetMirror.ts). Release builds otherwise refuse all cleartext traffic.
//
// Why cleartext is acceptable: integrity never came from the transport. Every mirrored byte is
// checked against the size and MD5 baked into the APK (src/config/model.ts,
// imagePacks.generated.json) before it is used, and a mismatch falls back to the canonical HTTPS
// host. A LAN laptop has no publicly trusted certificate, and TLS would add nothing that check
// does not already give.
//
// Why it is not narrower: a network security config can only name exact hosts or hostname
// suffixes. It has no IP ranges, and the laptop's address comes from whatever DHCP lease it holds
// that day, so the private ranges cannot be listed. The narrowing therefore lives in the app:
// the only http:// URLs it ever builds are mirror URLs, and those are refused unless the host is a
// literal RFC 1918 address. What this file CAN still pin is Hiraia's own domain, which stays
// HTTPS-only, so no code path can ever be downgraded to plain HTTP there.
const NAME = 'hiraia_network_security';
const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAssetMirrorCleartext.js; read the note there before editing. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="true">hiraia.org</domain>
  </domain-config>
</network-security-config>
`;

function withAssetMirrorCleartext(config) {
  config = withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
    // With a config present, Android ignores usesCleartextTraffic (including the debug
    // manifest's), so this file is the single answer for every build type.
    app.$['android:networkSecurityConfig'] = `@xml/${NAME}`;
    return config;
  });
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const dir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${NAME}.xml`), XML);
      return config;
    },
  ]);
}

module.exports = withAssetMirrorCleartext;
module.exports.XML = XML;
