/**
 * Inject QVAC/bare native addons (.so) into the app's jniLibs so they are
 * packaged into the APK.
 *
 * Why: the on-device worker (react-native-bare-kit) dlopen()s versioned addons
 * like `libbare-abort.2.0.13.so` and the QVAC engine `libqvac__llm-llamacpp.*.so`
 * at runtime. QVAC's gradle-time linker (react-native-bare-kit/android/link.mjs ->
 * src/main/addons) does NOT populate them in our pnpm monorepo, so the APK ships
 * with only `libbare-kit.so` and the worker aborts:
 *   AddonError: dlopen failed: library "libbare-abort.2.0.13.so" not found
 *
 * `bare-link` itself resolves the addons fine, so we run it ourselves at PREBUILD
 * time (which has node + the right cwd) and write into the app module's canonical
 * jniLibs dir, which gradle always packages into lib/<abi>/.
 *
 * We WIPE jniLibs first. bare-link only ever adds files, and the QVAC engines are
 * linked under VERSION-SUFFIXED names (libqvac__llm-llamacpp.0.39.3.so) while their
 * ggml backends are UNVERSIONED (libqvac-ggml-cpu-android_armv8.0_1.so). So an
 * SDK/engine upgrade in a long-lived android/ tree leaves the old engine .so behind
 * (dead weight in the APK — this is how the tree accumulated both llm-llamacpp
 * 0.20.1 and 0.24.0) while the unversioned backends get overwritten by whichever
 * engine linked last, i.e. a new engine paired with stale ggml backends. This
 * directory is 100% generated by this plugin, so recreating it from scratch each
 * prebuild is both safe and the only failure-closed option.
 *
 * ORDERING — this plugin MUST be listed BEFORE "@qvac/sdk/expo-plugin" in app.json.
 * Expo composes mods as a chain in which the LAST-registered action runs FIRST and
 * then calls the previously-registered one (@expo/config-plugins withMod.js: the
 * action awaits, then `return nextMod(results)`). We read qvac/addons.manifest.json,
 * which the SDK plugin rewrites during its own dangerous mod — so listing us AFTER it
 * makes us run BEFORE it and consume the PREVIOUS build's manifest. That silently
 * dropped `bare-cpu-info` / `bare-gpu-info` (new addons in SDK 0.17.1) from the APK on
 * the first prebuild after the upgrade. Listed first, we run last and see a fresh
 * manifest.
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

module.exports = function withQvacAddons(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const jniLibs = path.join(
        cfg.modRequest.platformProjectRoot, // android/
        'app',
        'src',
        'main',
        'jniLibs'
      );

      // Use the bundle's allowlist (qvac/addons.manifest.json, written by the
      // @qvac/sdk expo plugin earlier in prebuild) so we only link the engines we
      // actually bundled; fall back to linking everything installed.
      const manifestPath = path.join(projectRoot, 'qvac', 'addons.manifest.json');
      let pkg = null;
      if (fs.existsSync(manifestPath)) {
        const addons = JSON.parse(fs.readFileSync(manifestPath, 'utf8')).addons || [];
        if (addons.length > 0) {
          pkg = {
            name: 'qvac-addons',
            version: '0.0.0',
            dependencies: Object.fromEntries(addons.map((n) => [n, '*'])),
          };
        }
      }

      // Start from a clean slate — see the header comment.
      fs.rmSync(jniLibs, { recursive: true, force: true });

      const { default: link } = await import('bare-link');
      let count = 0;
      for await (const _resource of link(
        projectRoot,
        { hosts: ['android-arm64'], out: jniLibs },
        pkg
      )) {
        count++;
      }
      console.log(`[withQvacAddons] linked ${count} native addon(s) into app/src/main/jniLibs`);

      // BASELINE CPU BACKEND ONLY — the on-device fix for "no backends loaded" (measured
      // 2026-09-02 on the SM6225 test phone, CPU part 0x801, Features = fp asimd … crc32:
      // a plain armv8.0 core, no dotprod/i8mm/fp16). ggml auto-picks the HIGHEST-ISA CPU
      // backend present in the APK; on an armv8.0 core the armv8.2+/armv9 variants cannot
      // execute, the backend registry comes up EMPTY, and BOTH the Vulkan attempt and the
      // CPU-fallback retry die as MODEL_LOAD_FAILED 52200 with no native detail. This is
      // the kitten-era lesson, resolved for ONE apk by the pivot's own architecture:
      // CPU is only ever the FALLBACK now (flagships ride Vulkan at gpuLayers 99), so the
      // universal armv8.0 backend is the only CPU variant worth shipping — a flagship that
      // ever falls back loses some prefill speed, a budget phone gains a working tutor.
      // Vulkan and OpenCL stay; do NOT reintroduce gradle jniLibs excludes for this
      // (post-prebuild hard-fails on those — this filter is the sanctioned mechanism).
      const CPU_VARIANT = /^libqvac-ggml-cpu-android_armv(?!8\.0_)/;
      let dropped = 0;
      const abiDir = path.join(jniLibs, 'arm64-v8a');
      for (const f of fs.readdirSync(abiDir)) {
        if (CPU_VARIANT.test(f)) { fs.rmSync(path.join(abiDir, f)); dropped++; }
      }
      if (dropped) console.log(`[withQvacAddons] dropped ${dropped} non-baseline CPU backend variant(s) — armv8.0 is the universal fallback`);
      return cfg;
    },
  ]);
};
