from pathlib import Path
import base64

root = Path(__file__).resolve().parents[2]
out = Path(__file__).resolve().parent
faces = [('Alfa', 'alfa-slab-one-latin.woff2'), ('Patua', 'patua-one-latin.woff2'), ('Zilla', 'zilla-slab-700-latin.woff2')]
fonts = '\n'.join("@font-face{font-family:'%s';src:url(data:font/woff2;base64,%s) format('woff2');font-weight:400;}" % (name, base64.b64encode((root/'packages/web/public/fonts'/file).read_bytes()).decode()) for name,file in faces)
asterisk = '<svg viewBox="0 0 40 40" aria-hidden="true"><g stroke="currentColor" stroke-width="5.5" stroke-linecap="round"><path d="M20 6v28M8 13l24 14M8 27l24-14"/></g></svg>'
flower = '<svg viewBox="0 0 40 40" aria-hidden="true"><g fill="currentColor">' + ''.join(f'<ellipse cx="20" cy="10" rx="4.4" ry="7.5" transform="rotate({a} 20 20)"/>' for a in range(0,360,60)) + '<circle cx="20" cy="20" r="4.7"/></g></svg>'
leaf = '<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M20 32C6 31 3 19 5 10c11-1 18 8 15 22ZM21 32C18 15 24 7 36 5c1 15-5 24-15 27Z" fill="currentColor"/></svg>'
options = [
 ('a','01 / familiar','Alfa','asterisk',asterisk,'The smallest step','The existing slab, in lowercase, with tighter spacing and a rounded asterisk. Familiar and sturdy.'),
 ('b','02 / softer','Patua','flower',flower,'A little more warmth','Softer serifs and a six-petal raised flower. More open, less heavy; my starting point for refinement.'),
 ('c','03 / bookish','Zilla','leaf',leaf,'Quiet curiosity','A lighter slab with a tiny two-leaf glyph. More like a friendly book imprint; the furthest from the original.'),
]
def mark(cls, glyph):
 return f'<span class="mark {cls}" role="img" aria-label="hiraia">hiraia<span class="glyph">{glyph}</span></span>'
cards=''
for cls,label,font,glyphname,glyph,title,desc in options:
 cards+=f'<article><div class="eyebrow">{label}</div><div class="specimen">{mark(cls,glyph)}</div><h2>{title}</h2><p>{desc}</p><div class="small-label">At website-header size</div><div class="nav-sample">{mark(cls,glyph)}<span>About ↗</span></div><div class="reverse">{mark(cls,glyph)}</div></article>'
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>hiraia — wordmark studies</title><style>'''+fonts+'''
*{box-sizing:border-box}body{margin:0;background:#f5ecd6;color:#1c3b2e;font-family:system-ui,-apple-system,sans-serif}main{max-width:1240px;margin:auto;padding:48px 40px 32px}.top{display:flex;justify-content:space-between;align-items:center;gap:24px;border-bottom:1px solid #1c3b2e33;padding-bottom:25px}.eyebrow,.small-label{font-size:11px;letter-spacing:.12em;text-transform:uppercase}.current{font-family:Alfa;font-size:24px;letter-spacing:.06em}.current span{color:#d6a134}.current-label{font-size:11px;margin-top:4px;color:#5a6a5f}h1{font-size:30px;line-height:1.2;letter-spacing:-.04em;font-weight:500;margin:32px 0 10px}.intro{max-width:660px;font-size:16px;line-height:1.6;color:#506354;margin:0 0 32px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}article{border-top:2px solid #1c3b2e;padding-top:15px}.specimen{height:184px;display:flex;align-items:center;justify-content:center}.mark{display:inline-flex;align-items:baseline;white-space:nowrap;font-weight:400;line-height:1;letter-spacing:-.035em}.a{font-family:Alfa;font-size:76px;letter-spacing:-.047em}.b{font-family:Patua;font-size:88px;letter-spacing:-.029em}.c{font-family:Zilla;font-size:90px;letter-spacing:-.035em}.glyph{position:relative;top:-.46em;width:.27em;height:.27em;margin-left:.055em;display:inline-block;color:#c8942b;flex-shrink:0}.glyph svg{width:100%;height:100%;display:block}.b .glyph{width:.26em;height:.26em;top:-.46em;margin-left:.065em}.c .glyph{top:-.43em;width:.27em;height:.27em}h2{font-size:18px;font-weight:550;letter-spacing:-.025em;margin:0 0 9px}article p{font-size:14px;line-height:1.65;margin:0;min-height:92px;color:#506354}.small-label{color:#687b6b;margin:25px 0 12px;font-size:9px}.nav-sample{display:flex;align-items:center;justify-content:space-between;border-top:1px solid #1c3b2e22;border-bottom:1px solid #1c3b2e22;padding:19px 0}.nav-sample .mark{font-size:31px}.nav-sample>span:last-child{font-size:11px}.reverse{height:128px;margin-top:22px;background:#1c3b2e;display:flex;justify-content:center;align-items:center;color:#f5ecd6;border-radius:3px}.reverse .mark{font-size:49px}.reverse .glyph{color:inherit}footer{font-size:12px;line-height:1.65;color:#617365;border-top:1px solid #1c3b2e33;margin-top:34px;padding-top:19px}.note{font-size:11px;text-align:right;line-height:1.5;color:#617365}.actions{display:flex;align-items:center;gap:12px;margin-top:18px}button{font:inherit;font-size:12px;border:1px solid #1c3b2e55;border-radius:30px;padding:8px 13px;color:inherit;background:transparent;cursor:pointer}button:hover{background:#e9dec3}body.mono .glyph{color:inherit}body.mono .reverse .glyph{color:inherit}@media(max-width:900px){.grid{grid-template-columns:1fr}.specimen{height:160px}article{margin-bottom:18px}article p{min-height:0}.reverse{height:110px}main{padding:28px 24px}.top{align-items:start}h1{font-size:27px}}@media print{button{display:none}main{padding:20px}.grid{grid-template-columns:repeat(3,1fr)}}
</style><main><div class="top"><div><div class="current">HIRAIA<span>.</span></div><div class="current-label">Current direction</div></div><div class="note">WORDMARK STUDIES / 01<br>Same name. Same palette. A softer voice.</div></div><h1>A friendlier “hiraia”.</h1><p class="intro">Three small evolutions: lowercase lettering, more considered spacing, and a raised signature glyph. These are direction studies, before custom letterform drawing.</p><div class="grid">'''+cards+'''</div><div class="actions"><button onclick="document.body.classList.toggle('mono')">Toggle single colour</button><button onclick="window.print()">Print / save PDF</button></div><footer>The flower direction is my starting recommendation. Keep the glyph attached to the name, small enough to feel like a signature. The final wordmark would be drawn as SVG outlines with custom spacing, so it works consistently across web, Android, and print.</footer></main></html>'''
(out/'index.html').write_text(html)
print(out/'index.html')
