#!/usr/bin/env python3
"""Compile the curated fact bank (JSONL, source of truth) into a bundled
TypeScript module that the mobile + web apps import for on-device retrieval.

  python3 rag/scripts/export-facts-ts.py

Reads  rag/bank/science-facts.jsonl
Writes packages/shared/src/rag/facts.generated.ts

The emitted module is plain data (a typed array literal) — no native deps, so
it bundles in both Metro (mobile) and Vite (web). Edit the JSONL, then rerun.
"""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # rag/
ROOT = os.path.dirname(HERE)
JSONL = os.path.join(HERE, "bank", "science-facts.jsonl")
OUT = os.path.join(ROOT, "packages", "shared", "src", "rag", "facts.generated.ts")

FIELDS = ("id", "domain", "topic", "grades", "terms", "fact", "source", "generator", "reviewed")


def load():
    rows = []
    for line in open(JSONL, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        # Keep a stable field order; drop anything unexpected.
        rows.append({k: r[k] for k in FIELDS})
    return rows


def main():
    rows = load()
    # JSON is a valid TS expression; one fact per line keeps diffs readable.
    body = ",\n  ".join(json.dumps(r, ensure_ascii=False, sort_keys=False) for r in rows)
    out = (
        "// AUTO-GENERATED by rag/scripts/export-facts-ts.py — DO NOT EDIT.\n"
        "// Source of truth: rag/bank/science-facts.jsonl\n"
        f"// {len(rows)} facts.\n"
        'import type { ScienceFact } from \'./types.js\';\n\n'
        "export const SCIENCE_FACTS: ScienceFact[] = [\n  "
        + body
        + ",\n];\n"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {OUT}: {len(rows)} facts, {os.path.getsize(OUT)/1024:.0f} KB")


if __name__ == "__main__":
    main()
