import type { Language } from '@hiraia/shared';

const copy = {
  english: {
    title: 'Hiraia Tala',
    sectionJoin: 'JOIN A CLASS',
    scanQr: 'SCAN QR CODE',
    enterTheCode: 'Enter the Code ...',
    joinBody:
      'Join a Hiraia classroom by scanning a QR code on the Hiraia Tala teacher’s app. Joining a class will share this student’s activities with the teacher.',
    leaveClass: 'LEAVE CLASS',
    leaveBody: 'If you leave this class, your teacher will not be able to see your activities.',
    yourClass: 'YOUR CLASS',
    // Class membership is per student: the section names whose class it is.
    student: 'Student',
    // Matches the title bar, which shows "Guest" in every language.
    guest: 'Guest',
    rejoin:
      'Hiraia was updated: each student on this phone now joins a class on their own. Scan your teacher’s QR code again.',
    join: 'Join Hiraia Tala / Scan teacher QR',
    scan: 'Scan QR',
    enterCode: 'Enter code instead',
    codeHint: 'Type the 12-character code on the teacher phone (XXXX-XXXX-XXXX).',
    codeInvalid: 'That code is not valid. Check the teacher phone and try again.',
    codeExpired: 'That code expired or is wrong. Ask the teacher to show a new one, then retry.',
    leave: 'Leave class / Stop sharing',
    leaveConfirm: (name: string) =>
      `${name} will stop sending activity to that teacher. Other students on this phone stay in their own classes. Data already on the teacher phone is not erased.`,
    rebind:
      'This student is already in another class. Switch? The new teacher will receive this student’s card and quiz history still saved on this phone.',
    sync: 'Sync now',
    searching: 'Searching for the teacher phone…',
    connected: 'Connected',
    sending: 'Sending activity…',
    synced: 'Synced. This phone keeps looking while Hiraia is open.',
    idle: 'Ready. While Hiraia is open, this phone looks for the teacher on its own. You do not need to tap again. The teacher still taps Collect activity.',
    unbound: 'Not in a class. Scan the class QR, or enter the code on the teacher phone. The teacher assigns groups later.',
    playServices: 'Google Play services are required for classroom sync.',
    permission: 'Allow Nearby, Bluetooth, location, and camera so this phone can find the teacher.',
    nearby: 'Could not start Nearby. Check Bluetooth and Wi-Fi, then retry.',
    bluetoothOff: 'Turn on Bluetooth so this phone can find the teacher.',
    wifiOff: 'Turn on Wi-Fi so this phone can find the teacher.',
    radiosOff: 'Turn on Bluetooth and Wi-Fi so this phone can find the teacher.',
    bluetoothUnavailable: 'This phone does not support Bluetooth, which is needed for classroom sync.',
    wifiUnavailable: 'This phone does not support Wi-Fi, which is needed for classroom sync.',
    turnOnBluetooth: 'Turn on Bluetooth',
    openWifiSettings: 'Turn on Wi-Fi',
    invalid: 'That QR is not a Hiraia Tala class code.',
    cancel: 'Cancel',
    confirm: 'Continue',
    leaveBtn: 'Stop sharing',
  },
  tagalog: {
    title: 'Hiraia Tala',
    sectionJoin: 'SUMALI SA KLASE',
    scanQr: 'I-SCAN ANG QR CODE',
    enterTheCode: 'Ilagay ang Code ...',
    joinBody:
      'Sumali sa klase sa Hiraia sa pag-scan ng QR code sa app ng guro. Kapag sumali, makikita ng guro ang mga gawain ng mag-aaral na ito.',
    leaveClass: 'UMALIS SA KLASE',
    leaveBody: 'Kapag umalis ka, hindi na makikita ng guro mo ang mga gawain mo.',
    yourClass: 'ANG KLASE MO',
    student: 'Mag-aaral',
    guest: 'Guest',
    rejoin:
      'Na-update ang Hiraia: hiwalay nang sumasali sa klase ang bawat mag-aaral sa teleponong ito. I-scan muli ang QR code ng guro mo.',
    join: 'Sumali sa Hiraia Tala / I-scan ang QR ng guro',
    scan: 'I-scan ang QR',
    enterCode: 'Maglagay ng code',
    codeHint: 'I-type ang 12-titik na code sa telepono ng guro (XXXX-XXXX-XXXX).',
    codeInvalid: 'Hindi wasto ang code. Tingnan ang telepono ng guro at subukan muli.',
    codeExpired: 'Expired o mali ang code. Hingin sa guro ang bagong code, saka subukan muli.',
    leave: 'Umalis sa klase / Itigil ang pagbabahagi',
    leaveConfirm: (name: string) =>
      `Hihinto na si ${name} sa pagpapadala ng activity sa gurong iyon. Mananatili sa sarili nilang klase ang ibang mag-aaral sa teleponong ito. Hindi mabubura ang datos na nasa telepono na ng guro.`,
    rebind:
      'Nasa ibang klase na ang mag-aaral na ito. Palitan? Matatanggap ng bagong guro ang kasaysayan ng mga card at quiz ng mag-aaral na ito na naka-save pa sa teleponong ito.',
    sync: 'I-sync ngayon',
    searching: 'Naghahanap ng telepono ng guro…',
    connected: 'Nakakonekta',
    sending: 'Ipinapadala ang activity…',
    synced: 'Na-sync. Patuloy ang paghahanap habang bukas ang Hiraia.',
    idle: 'Handa na. Habang bukas ang Hiraia, maghahanap mag-isa ang teleponong ito ng guro. Hindi na kailangang pindutin ulit. Ang Collect activity ay sa guro pa rin.',
    unbound: 'Wala sa klase. I-scan ang QR ng klase, o i-type ang code sa telepono ng guro. Ang guro ang magtatalaga ng grupo mamaya.',
    playServices: 'Kailangan ang Google Play services para sa classroom sync.',
    permission: 'Payagan ang Nearby, Bluetooth, location, at camera para mahanap ang guro.',
    nearby: 'Hindi masimulan ang Nearby. Tingnan ang Bluetooth at Wi-Fi, saka subukan muli.',
    bluetoothOff: 'I-on ang Bluetooth para mahanap ng teleponong ito ang guro.',
    wifiOff: 'I-on ang Wi-Fi para mahanap ng teleponong ito ang guro.',
    radiosOff: 'I-on ang Bluetooth at Wi-Fi para mahanap ng teleponong ito ang guro.',
    bluetoothUnavailable: 'Walang Bluetooth ang teleponong ito, na kailangan para sa classroom sync.',
    wifiUnavailable: 'Walang Wi-Fi ang teleponong ito, na kailangan para sa classroom sync.',
    turnOnBluetooth: 'I-on ang Bluetooth',
    openWifiSettings: 'I-on ang Wi-Fi',
    invalid: 'Hindi iyon QR ng Hiraia Tala.',
    cancel: 'Ikansela',
    confirm: 'Magpatuloy',
    leaveBtn: 'Itigil ang pagbabahagi',
  },
  cebuano: {
    title: 'Hiraia Tala',
    sectionJoin: 'APIL SA KLASE',
    scanQr: 'I-SCAN ANG QR CODE',
    enterTheCode: 'Isulod ang Code ...',
    joinBody:
      'Apil sa klase sa Hiraia pinaagi sa pag-scan sa QR code sa app sa magtutudlo. Inig-apil, makita sa magtutudlo ang mga buhat niining estudyante.',
    leaveClass: 'MOBIYA SA KLASE',
    leaveBody: 'Kon mobiya ka, dili na makita sa imong magtutudlo ang imong mga buhat.',
    yourClass: 'ANG IMONG KLASE',
    student: 'Estudyante',
    guest: 'Guest',
    rejoin:
      'Karon, ang matag estudyante niining telepono kinahanglan moapil sa klase. I-scan pag-usab ang QR code sa imong magtutudlo.',
    join: 'Apil sa Hiraia Tala / I-scan ang QR sa magtutudlo',
    scan: 'I-scan ang QR',
    enterCode: 'Ibutang ang code',
    codeHint: 'I-type ang 12-ka-karakter nga code sa telepono sa magtutudlo (XXXX-XXXX-XXXX).',
    codeInvalid: 'Dili sakto ang code. Tan-awa ang telepono sa magtutudlo ug sulayi pag-usab.',
    codeExpired: 'Expired o sayop ang code. Pangayoa ang bag-ong code, dayon sulayi pag-usab.',
    leave: 'Mobiya sa klase / Hunonga ang pagpaambit',
    leaveConfirm: (name: string) =>
      `Mohunong na si ${name} sa pagpadala og activity ngadto sa magtutudlo. Ang ubang estudyante niining telepono magpabilin sa ilang kaugalingong klase. Dili mapapas ang datos nga naa na sa telepono sa magtutudlo.`,
    rebind:
      'Naa na sa laing klase kining estudyante. Ilisan? Madawat sa bag-ong magtutudlo ang kasaysayan sa mga card ug quiz niining estudyante nga naka-save pa niining telepono.',
    sync: 'I-sync karon',
    searching: 'Nangita sa telepono sa magtutudlo…',
    connected: 'Nakakonektar',
    sending: 'Gipadala ang activity…',
    synced: 'Na-sync. Magpadayon og pangita samtang abli ang Hiraia.',
    idle: 'Andam na. Samtang abli ang Hiraia, mangita kini sa magtutudlo nga walay laing pindot. Ang Collect activity anaa gihapon sa magtutudlo.',
    unbound: 'Wala sa klase. I-scan ang QR sa klase, o i-type ang code sa telepono sa magtutudlo. Ang magtutudlo mag-assign og grupo unya.',
    playServices: 'Gikinahanglan ang Google Play services para sa classroom sync.',
    permission: 'Tugoti ang Nearby, Bluetooth, location, ug kamera aron makit-an ang magtutudlo.',
    nearby: 'Dili masugdan ang Nearby. Tan-awa ang Bluetooth ug Wi-Fi, dayon sulayi pag-usab.',
    bluetoothOff: 'I-on ang Bluetooth aron makit-an niining telepono ang magtutudlo.',
    wifiOff: 'I-on ang Wi-Fi aron makit-an niining telepono ang magtutudlo.',
    radiosOff: 'I-on ang Bluetooth ug Wi-Fi aron makit-an niining telepono ang magtutudlo.',
    bluetoothUnavailable: 'Walay Bluetooth kining telepono, nga gikinahanglan para sa classroom sync.',
    wifiUnavailable: 'Walay Wi-Fi kining telepono, nga gikinahanglan para sa classroom sync.',
    turnOnBluetooth: 'I-on ang Bluetooth',
    openWifiSettings: 'I-on ang Wi-Fi',
    invalid: 'Dili kana QR sa Hiraia Tala.',
    cancel: 'Kanselahon',
    confirm: 'Padayon',
    leaveBtn: 'Hunonga ang pagpaambit',
  },
} as const;

export function talaCopy(language: Language) {
  return copy[language] ?? copy.tagalog;
}
